// ============================================
// AgentBridge - Domain Enums
// ============================================

// ---- Purchase lifecycle ----

export enum PurchaseStatus {
  CREATED = 'CREATED',
  EVALUATING = 'EVALUATING',
  AUTHORIZED = 'AUTHORIZED',
  REQUIRE_APPROVAL = 'REQUIRE_APPROVAL',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  BLOCKED = 'BLOCKED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

/**
 * The authoritative transition table. Every state change in the system is
 * validated against this map inside the same database transaction that
 * performs the write — see `assertTransition` in the API's state guard.
 */
export const VALID_TRANSITIONS: Record<PurchaseStatus, PurchaseStatus[]> = {
  [PurchaseStatus.CREATED]: [
    PurchaseStatus.EVALUATING,
    PurchaseStatus.EXPIRED,
    PurchaseStatus.CANCELLED,
  ],
  [PurchaseStatus.EVALUATING]: [
    PurchaseStatus.AUTHORIZED,
    PurchaseStatus.REQUIRE_APPROVAL,
    PurchaseStatus.BLOCKED,
  ],
  [PurchaseStatus.AUTHORIZED]: [
    PurchaseStatus.PAYMENT_PENDING,
    PurchaseStatus.EXPIRED,
    PurchaseStatus.CANCELLED,
    // Re-evaluation after a policy change can retract an authorization.
    PurchaseStatus.BLOCKED,
  ],
  [PurchaseStatus.REQUIRE_APPROVAL]: [
    PurchaseStatus.APPROVED,
    PurchaseStatus.DENIED,
    PurchaseStatus.EXPIRED,
    PurchaseStatus.CANCELLED,
  ],
  [PurchaseStatus.APPROVED]: [PurchaseStatus.AUTHORIZED, PurchaseStatus.EXPIRED],
  [PurchaseStatus.PAYMENT_PENDING]: [
    PurchaseStatus.PAYMENT_PROCESSING,
    PurchaseStatus.FAILED,
    PurchaseStatus.EXPIRED,
  ],
  [PurchaseStatus.PAYMENT_PROCESSING]: [PurchaseStatus.COMPLETED, PurchaseStatus.FAILED],
  // Terminal states.
  [PurchaseStatus.DENIED]: [],
  [PurchaseStatus.BLOCKED]: [],
  [PurchaseStatus.COMPLETED]: [],
  [PurchaseStatus.FAILED]: [],
  [PurchaseStatus.EXPIRED]: [],
  [PurchaseStatus.CANCELLED]: [],
};

/** States that count against an agent's spending budget (reserved or spent). */
export const BUDGET_CONSUMING_STATES: PurchaseStatus[] = [
  PurchaseStatus.AUTHORIZED,
  PurchaseStatus.PAYMENT_PENDING,
  PurchaseStatus.PAYMENT_PROCESSING,
  PurchaseStatus.COMPLETED,
];

// ---- Decisions ----

export enum PolicyDecision {
  ALLOW = 'ALLOW',
  REQUIRE_APPROVAL = 'REQUIRE_APPROVAL',
  BLOCK = 'BLOCK',
}

/** Decision precedence: BLOCK > REQUIRE_APPROVAL > ALLOW. Higher wins. */
export const DECISION_PRECEDENCE: Record<PolicyDecision, number> = {
  [PolicyDecision.ALLOW]: 0,
  [PolicyDecision.REQUIRE_APPROVAL]: 1,
  [PolicyDecision.BLOCK]: 2,
};

/** Returns the most restrictive of two decisions. */
export function mostRestrictive(a: PolicyDecision, b: PolicyDecision): PolicyDecision {
  return DECISION_PRECEDENCE[a] >= DECISION_PRECEDENCE[b] ? a : b;
}

// ---- Policy rules ----

/** Every rule the deterministic policy engine can evaluate, in evaluation order. */
export enum PolicyRule {
  AGENT_STATUS = 'AGENT_STATUS',
  AGENT_PERMISSION = 'AGENT_PERMISSION',
  PERMISSION_EXPIRY = 'PERMISSION_EXPIRY',
  POLICY_EXPIRY = 'POLICY_EXPIRY',
  CURRENCY_ALLOWED = 'CURRENCY_ALLOWED',
  MERCHANT_ALLOWED = 'MERCHANT_ALLOWED',
  CATEGORY_ALLOWED = 'CATEGORY_ALLOWED',
  MAX_TRANSACTION_AMOUNT = 'MAX_TRANSACTION_AMOUNT',
  DAILY_SPEND_LIMIT = 'DAILY_SPEND_LIMIT',
  DAILY_TRANSACTION_COUNT = 'DAILY_TRANSACTION_COUNT',
  VELOCITY_LIMIT = 'VELOCITY_LIMIT',
  TIME_WINDOW = 'TIME_WINDOW',
  RISK_BLOCK_THRESHOLD = 'RISK_BLOCK_THRESHOLD',
  RISK_APPROVAL_THRESHOLD = 'RISK_APPROVAL_THRESHOLD',
  APPROVAL_AMOUNT_THRESHOLD = 'APPROVAL_AMOUNT_THRESHOLD',
}

/** Machine-readable reason for a decision. Stable across releases. */
export enum ReasonCode {
  OK = 'OK',
  AGENT_NOT_ACTIVE = 'AGENT_NOT_ACTIVE',
  AGENT_PERMISSION_DENIED = 'AGENT_PERMISSION_DENIED',
  PERMISSION_EXPIRED = 'PERMISSION_EXPIRED',
  POLICY_EXPIRED = 'POLICY_EXPIRED',
  CURRENCY_NOT_ALLOWED = 'CURRENCY_NOT_ALLOWED',
  MERCHANT_NOT_ALLOWED = 'MERCHANT_NOT_ALLOWED',
  CATEGORY_NOT_ALLOWED = 'CATEGORY_NOT_ALLOWED',
  TRANSACTION_LIMIT_EXCEEDED = 'TRANSACTION_LIMIT_EXCEEDED',
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  DAILY_COUNT_EXCEEDED = 'DAILY_COUNT_EXCEEDED',
  VELOCITY_EXCEEDED = 'VELOCITY_EXCEEDED',
  OUTSIDE_ALLOWED_HOURS = 'OUTSIDE_ALLOWED_HOURS',
  RISK_TOO_HIGH = 'RISK_TOO_HIGH',
  RISK_REQUIRES_APPROVAL = 'RISK_REQUIRES_APPROVAL',
  APPROVAL_THRESHOLD_EXCEEDED = 'APPROVAL_THRESHOLD_EXCEEDED',
}

// ---- Actors & audit ----

export enum ActorType {
  AGENT = 'AGENT',
  SYSTEM = 'SYSTEM',
  MERCHANT_USER = 'MERCHANT_USER',
  PAYMENT_PROVIDER = 'PAYMENT_PROVIDER',
}

export enum AuditAction {
  // Catalog
  PRODUCT_SEARCHED = 'PRODUCT_SEARCHED',
  PRODUCT_VIEWED = 'PRODUCT_VIEWED',
  // Identity
  AGENT_REGISTERED = 'AGENT_REGISTERED',
  AGENT_AUTHENTICATED = 'AGENT_AUTHENTICATED',
  AGENT_AUTH_FAILED = 'AGENT_AUTH_FAILED',
  MERCHANT_USER_AUTHENTICATED = 'MERCHANT_USER_AUTHENTICATED',
  // Purchase
  PURCHASE_INTENT_CREATED = 'PURCHASE_INTENT_CREATED',
  POLICY_EVALUATED = 'POLICY_EVALUATED',
  THREAT_ANALYSIS_COMPLETED = 'THREAT_ANALYSIS_COMPLETED',
  PURCHASE_ALLOWED = 'PURCHASE_ALLOWED',
  PURCHASE_BLOCKED = 'PURCHASE_BLOCKED',
  BUDGET_RESERVED = 'BUDGET_RESERVED',
  BUDGET_RELEASED = 'BUDGET_RELEASED',
  // Approval
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_DENIED = 'APPROVAL_DENIED',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  APPROVAL_REPLAY_REJECTED = 'APPROVAL_REPLAY_REJECTED',
  // Payment
  PAYMENT_ORDER_CREATED = 'PAYMENT_ORDER_CREATED',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  WEBHOOK_REJECTED = 'WEBHOOK_REJECTED',
  WEBHOOK_REPLAY_REJECTED = 'WEBHOOK_REPLAY_REJECTED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  // Security
  SECURITY_VIOLATION_DETECTED = 'SECURITY_VIOLATION_DETECTED',
  REQUEST_BLOCKED_SECURITY = 'REQUEST_BLOCKED_SECURITY',
  REPLAY_ATTACK_DETECTED = 'REPLAY_ATTACK_DETECTED',
  IDEMPOTENCY_CONFLICT_DETECTED = 'IDEMPOTENCY_CONFLICT_DETECTED',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  HIGH_THREAT_DETECTED = 'HIGH_THREAT_DETECTED',
  CRITICAL_THREAT_DETECTED = 'CRITICAL_THREAT_DETECTED',
  AGENT_QUARANTINED = 'AGENT_QUARANTINED',
  AGENT_UNQUARANTINED = 'AGENT_UNQUARANTINED',
  AGENT_BLOCKED_PERMANENT = 'AGENT_BLOCKED_PERMANENT',
  AGENT_SECURITY_REVIEWED = 'AGENT_SECURITY_REVIEWED',
  // Policy
  POLICY_CHANGED = 'POLICY_CHANGED',
}

// ---- Agent status ----

export enum AgentStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  QUARANTINED = 'QUARANTINED',
  BLOCKED = 'BLOCKED',
}

// ---- Approval ----

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  EXPIRED = 'EXPIRED',
}

// ---- Payment ----

export enum PaymentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
}

// ---- Security violations ----

export enum SecurityViolation {
  UNKNOWN_AGENT = 'UNKNOWN_AGENT',
  INACTIVE_AGENT = 'INACTIVE_AGENT',
  MISSING_CREDENTIALS = 'MISSING_CREDENTIALS',
  INVALID_REQUEST_SIGNATURE = 'INVALID_REQUEST_SIGNATURE',
  EXPIRED_REQUEST = 'EXPIRED_REQUEST',
  REPLAY_ATTACK = 'REPLAY_ATTACK',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CROSS_TENANT_ACCESS = 'CROSS_TENANT_ACCESS',
  APPROVAL_REPLAY = 'APPROVAL_REPLAY',
  SELF_APPROVAL_ATTEMPT = 'SELF_APPROVAL_ATTEMPT',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_REPLAY = 'WEBHOOK_REPLAY',
  EXTREME_REQUEST_FREQUENCY = 'EXTREME_REQUEST_FREQUENCY',
}

/**
 * Violations that indicate deliberate attack rather than client error.
 * These drive quarantine escalation.
 */
export const SEVERE_SECURITY_EVENTS: string[] = [
  SecurityViolation.REPLAY_ATTACK,
  SecurityViolation.IDEMPOTENCY_CONFLICT,
  SecurityViolation.INVALID_REQUEST_SIGNATURE,
  SecurityViolation.INVALID_STATE_TRANSITION,
  SecurityViolation.CROSS_TENANT_ACCESS,
  SecurityViolation.APPROVAL_REPLAY,
  SecurityViolation.SELF_APPROVAL_ATTEMPT,
  SecurityViolation.WEBHOOK_SIGNATURE_INVALID,
  SecurityViolation.WEBHOOK_REPLAY,
  SecurityViolation.EXTREME_REQUEST_FREQUENCY,
];

export enum QuarantineTrigger {
  SECURITY_VIOLATION = 'SECURITY_VIOLATION',
  AUTOMATIC_THREAT_DETECTION = 'AUTOMATIC_THREAT_DETECTION',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

// ---- Threat engine ----

export enum ThreatLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ThreatAction {
  CONTINUE = 'CONTINUE',
  REQUIRE_APPROVAL = 'REQUIRE_APPROVAL',
  BLOCK = 'BLOCK',
  QUARANTINE_AGENT = 'QUARANTINE_AGENT',
}

export enum ThreatRule {
  HIGH_REQUEST_FREQUENCY = 'HIGH_REQUEST_FREQUENCY',
  EXTREME_REQUEST_FREQUENCY = 'EXTREME_REQUEST_FREQUENCY',
  REPEATED_BLOCKED_ATTEMPTS = 'REPEATED_BLOCKED_ATTEMPTS',
  EXCESSIVE_BLOCKED_ATTEMPTS = 'EXCESSIVE_BLOCKED_ATTEMPTS',
  REPEATED_POLICY_PROBING = 'REPEATED_POLICY_PROBING',
  REPEATED_NEAR_LIMIT_ATTEMPTS = 'REPEATED_NEAR_LIMIT_ATTEMPTS',
  UNUSUAL_SPENDING_SPIKE = 'UNUSUAL_SPENDING_SPIKE',
  RAPID_ESCALATION = 'RAPID_ESCALATION',
  SUSPICIOUS_CATEGORY_SWITCHING = 'SUSPICIOUS_CATEGORY_SWITCHING',
  REPEATED_DENIED_APPROVALS = 'REPEATED_DENIED_APPROVALS',
  MULTIPLE_SECURITY_WARNINGS = 'MULTIPLE_SECURITY_WARNINGS',
}

/** Threat score band boundaries. Single source of truth for level mapping. */
export const THREAT_BANDS = {
  CRITICAL: 80,
  HIGH: 60,
  MEDIUM: 30,
} as const;
